Deleted unneded files + added 7-9 ex with tests
secrierum/my_py pull request #4
Opened 2023-09-20 14:55 UTC by secrierum

2023-09-20 19:22 UTC, secrierum commented on test_reverse.py
formatter added an empty line for some reason

2023-09-21 07:10 UTC, vbrenister requested changes

2023-09-21 13:31 UTC, vbrenister commented on member.py
> +def is_member2(itm, lst):
```def is_member2(itm, lst):
        for elem in lst:
            return True
         return False
```

2023-09-21 14:11 UTC, vbrenister approved these changes

2023-09-21 14:18 UTC, merged